#!/usr/bin/env python3

"""
truckersmp-cli main script.

This script downloads/updates games and starts games with Wine/Proton.
"""

from truckersmp_cli import main

if __name__ == "__main__":
    main()
