#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: truckersmp-cli GAMEDIR"
    exit
fi

listurl=https://update.ets2mp.com
dlurl=https://downloads.ets2mp.com/files
dlurlalt=https://download.ets2mp.com/files
base="$(dirname "$0")"
dldir="truckersmp"

curdir=$(pwd)
cd "$base" || exit 1

mkdir -p "./$dldir"
wget --header 'Accept-encoding: identity' -O - "$listurl/files.json" > "./files.json" || exit 1

awk 'BEGIN{i=0}/":"/{printf $0;i=1;next}{if (i) {printf "\n"; i=0}}' "./files.json" | awk -F '"' '{printf "%s ./truckersmp%s\n",$8,$4}' > "./.checksums"

error=1
while [ "$error" = "1" ]; do
    files="$(cat "./.checksums" | md5sum -c --quiet - 2> /dev/null | awk -F ':' '{print $1}' | sed 's,\./'"$dldir"'/,,g')"
    error=0
    for f in $files; do
        mkdir -p "./$dldir/$(dirname "$f")"
        wget --header 'Accept-encoding: identity' -O - "$dlurl/$f" > "./$dldir/$f" || wget --header 'Accept-encoding: identity' -O - "$dlurlalt/$f" > "./$dldir/$f" || error=1
    done
    if [ "$error" = "1" ]; then
        echo ""
        echo "#####"
        echo "#/!\\#"
        echo "#####"
        echo ""
        echo "/!\\ Failed to download mod files. Try again? [Y/N]"
        old_stty_cfg=$(stty -g)
        stty raw -echo ; answer="$(head -c 1)" ; stty "$old_stty_cfg" # Careful playing with stty
        if echo "$answer" | grep -iq "^y" ;then
            "$0" "$@"; exit 0
        else
            exit 1
        fi
    fi
done

rm -f "./.checksums"

echo ""
echo "###################################################################"
echo "#                                                                 #"
echo "#  Please check that steam is running or the launcher won't work  #"
echo "#                                                                 #"
echo "###################################################################"
echo ""
echo "Press enter if you are good to go:"
read _

cd "$curdir"

WINEDEBUG=-all,WINEARCH=win64 wine "$base/truckersmp-cli.exe" "$1" "$base/$dldir"
